KNOWN_ARTICLES = {
    "Boots and Shoes", "Gold Thread and Lace", "Hats and Caps", "Millinery",
    "Wearing Apparel", "Bamboos and Blinds", "Bangles", "Beads", "Books",
    "Stationery", "Bones", "Cabinet-Ware", "Carriages", "Bullocks", "Horses",
    "Sheep", "Other Sorts", "Chanks", "Coffee", "Cotton Wool", "Twist and Yarn",
    "Piece Goods, Dyed", "Piece Goods Dyed", "Do. Printed", "Do. Plain",
    "Lace and Small Ware", "Cowries", "Dregs of Gingely Oil", "Aloes", "Camphor",
    "Cocculus Indicus", "Cuscus Root", "Gallingal", "Gallnuts", "Myrabolanes",
    "Nux Vomica", "Senna Leaves", "Zedore Zerumbeth", "Catechu or Terrajaponica",
    "Indigo", "Turmeric", "Emigrants' Stores", "Feathers", "Firewood", "Fishmaws",
    "Betel-nut, Boiled", "Betel-nut, Raw", "Cocoanuts", "Do. Kernels", "Dates",
    "Tamarind", "Goolal Powder", "Glassware of Sorts", "Anoomooloo",
    "Caramunloo", "Condooloo", "Dholl", "Horse Gram", "Menoomooloo",
    "Natcheny", "Paddy", "Peas", "Pessaloo", "Rice", "Sanagaloo", "Wheat",
    "Granite Slabs", "Grinding Stones", "Gum - Benjamin", "Gunnies and Gunny-Bags",
    "Hides, Tanned", "Hides, Untanned", "Honey", "Horns, Buffaloe",
    "Do. Bullock", "Do. Deer", "Hooka Shells", "Ivory and Elephant's Teeth",
    "Do. and Hornware", "Jewellery of Sorts", "Lac-Stick", "Do. Shell",
    "Brassware", "Copperware", "Ironware", "Silverware", "Machinery", "Mats",
    "Medicines", "Copper - Old", "Iron - Old", "Brass",
    "Military Stores - On Govt. account", "Molasses or Jagree", "Do. Palmirah",
    "Coir and Coir Rope", "Grease or Tallow", "Hemp", "Twine", "Cassia",
    "Castor", "Cocoanut", "Fish", "Gingely", "Ground-nut or Manilla", "Lamp",
    "Linseed", "Margosa", "Pinnay", "Oilman's Stores", "Sandal Oil",
    "Perfumery, Other Sorts", "Pipe Staves and Casks", "Pictures and Portraits",
    "Porcelain and Earthenware", "Pearls", "Rubies", "Printing Materials",
    "Arrow-root", "Confectionary", "Fresh", "Ghee", "Salted", "Reeds",
    "Saddlery", "Salt - On Private account", "Saltpetre", "Adjovan",
    "Coriander", "Cotton", "Croton", "Cummin", "Fenegreek", "Mustard", "Nigar",
    "Rape", "Valasaloo", "Shark-fins", "Shawls - Cashmere", "Ships' Stores",
    "Silk Raw", "Silk Piece Goods", "Soap", "Do. Earth", "Cardamums",
    "Chillies", "Cinnamon", "Ginger", "Mace", "Nutmegs", "Pepper",
    "Do. Long", "Do. White", "Arrack", "Rum", "Sugar", "Do. Candy",
    "Do. do. Palmirah", "Poon", "Jungle", "Teak - On private account",
    "Tobacco, Manufactured", "Tobacco, Unmanufactured", "Tortoise shells",
    "Toys", "Trunks and Boxes", "Umbrellas", "Wax and Wax Candles", "Black",
    "Ebony", "Red", "Sandal", "Sapan", "Woodenware", "Wool", "Blankets",
    "Carpets", "Cumblies", "Shawls", "Sundries", "Lamp Oil",
}
